---
# Playbook for deploying a Calibre Library, optionally also exposed
# as Tor Onion service, that can also be administered by SSH over Tor.
- name: Deploy Calibre content server and Tor server if requested.
  hosts: all
  remote_user: pi # Assume a Raspberry Pi running Raspbian by default.
  become: yes     # We'll need superuser privileges, so, ask for them.

  vars_files:
    - vars.yml

  pre_tasks:

    - name: Run common tasks.
      include_tasks: "tasks/common.yml"
    - name: Run hardening tasks.
      when: hardened_hosts
      include_tasks: "tasks/harden.yml"

  roles:
    - role: tor
      when: tor_onion_service_server
    - calibre
