# This file contains references to externally-supplied Ansible roles
# required for the project.
---
- name: common
  src: https://github.com/AnarchoTechNYC/ansible-role-common
  scm: git
  # The `master` version is the default.
  #version: master

- name: tor
  src: https://github.com/AnarchoTechNYC/ansible-role-tor
  scm: git

- name: onionshare
  src: https://github.com/AnarchoTechNYC/ansible-role-onionshare
  scm: git

- name: lighttpd
  src: https://github.com/AnarchoTechNYC/ansible-role-lighttpd
  scm: git

- name: calibre
  src: https://github.com/shiftctrlspace/ansible-role-calibre
  scm: git
