# Tasks for hardening the base of a Debian-dervied OS host.

# TODO: Extract what can be generalized here to RedHat-based systems.
- name: Install base hardening packages.
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - iptables
