---
# Tasks for hardening the base of a Debian-dervied OS host.

- name: Install base hardening packages.
  apt:
    update_cache: true
    name: "{{ packages }}"
  vars:
    packages:
      - iptables
      - iptables-persistent

- name: Configure iptables firewall rules.
  register: configure_iptables
  template:
    src: "templates/iptables.{{ item }}"
    dest: "/etc/iptables/{{ item }}"
  loop:
    - rules.v4
    - rules.v6

- name: Apply new firewall configuration.
  when: configure_iptables is changed
  command: "{{ item }}"
  loop:
    - "iptables-restore /etc/iptables/rules.v4"
    - "ip6tables-restore /etc/iptables/rules.v6"

- name: Include Raspbian-specific hardening tasks.
  include_tasks: "harden-raspbian.yml"
