---
# Playbook for deploying a Calibre Library, optionally also exposed
# as Tor Onion service, that can also be administered by SSH over Tor.
- name: Provision Library nodes with Dark Web access if requested.
  hosts: all
  become: yes

  pre_tasks:
    - name: Run common tasks.
      include_tasks: "tasks/common.yml"
    - name: Run hardening tasks.
      when: hardened_hosts
      include_tasks: "tasks/harden.yml"

  roles:
    - role: tor
      when: tor_onion_service_server
    - calibre
