---
- name: Provision Library nodes with Dark Web access if requested.
  hosts: all
  become: true

  pre_tasks:
    - name: Register firewall configuration.
      import_tasks: tasks/configure-firewall.yml

  roles:
    - common
    - role: tor
      when:
        - tor_onion_service_server | default(false)
    - calibre
    - lighttpd

  tasks:
    - name: Install Calibre Content server resources.
      when: calibre_server_resources_files is defined
      copy:
        src: "{{ calibre_server_resources_files }}/content_server"
        dest: "{{ calibre_server_home_dir }}/.config/calibre/resources/"
        owner: "{{ calibre_server_username }}"
      notify: Restart Calibre.

    - name: Create Web landing page.
      when: web_landing_page_resources_dir is defined
      block:
        - name: Install Web landing page files.
          ignore_errors: true # It's possible we have no files to copy. :)
          synchronize:
            src: "files/{{ web_landing_page_resources_dir }}/"
            dest: /var/www/html/
            recursive: true
            rsync_opts:
              - "--exclude=.git"

        - name: Ensure Web landing page directory structure exists.
          when: item.state == "directory"
          file:
            path: "/var/www/html/{{ item.path }}"
            state: directory
          with_filetree: "templates/{{ web_landing_page_resources_dir }}"

        - name: Write Web landing page templates.
          when: item.state == "file"
          template:
            src: "{{ item.src }}"
            dest: "/var/www/html/{{ item.path }}"
          with_filetree: "templates/{{ web_landing_page_resources_dir }}"
