# Playbook for populating a Library with content from a sync source.
---
- name: Synchronize Library branches.
  hosts: all
  gather_facts: false

  tasks:
    - name: Send local books to Library branch.
      synchronize:
        src: "{{ item.sync_source }}"
        dest: "'{{ item.library_dir }}'" # Quote to escape spaces.
        archive: false
        recursive: true
        delete: true
        partial: true
        private_key: "~/.ssh/{{ inventory_hostname }}{{ calibre_server_home_dir }}/.ssh/{{ calibre_server_username }}_librarian_ed25519"
        set_remote_user: false
        # This is undocumented on the module page but is described on
        # the `ansible.cfg` config file documentation.
        ssh_args: "-l {{ calibre_server_username }}"
      loop: "{{ calibre_libraries }}"
